import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import MainLayout from '../layouts/Main'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <MainLayout>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Witaj na stronie z narzędziami do <a href="https://td2.info.pl">Symulatora TD2!</a>
        </h1>

        <p className={styles.description}>
          Znajdziesz tu szereg narzędzi przydatnych podczas rozgrywki!
        </p>

        <div className={styles.grid}>
          <Link href="train-number">
            <a className={styles.card}>
              <h2>Generator Numerów Pociągów &rarr;</h2>
              <p>Wygeneruj numer pociagu zgodny z regulaminem symulatora TD2!</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
    </MainLayout>
  )
}

export default Home
